---
- name: First Play
  hosts:  all
  tasks:
    - name: Create a Dir
      file:
        - path: /opt/redhat_dir
          state:  directory
        - copy:
          content:  "This is a test file"
          dest: /opt/redhat_dir/redhat_file
